name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: ./dist/
